### ISSUE TITLE
Example program displays leak count when built in release but memory tracker is not used?

### ISSUE THREAD

**Issue by EmbeddedTrickery** [BossKoopa/BWSR#1]
The memory tracker is not used in release mode the example it includes a leak count regardless. This is always 0 even if leaks are introduced, it works correctly in debug mode.

**Comment by BossKoopa** [comment]
It will now be defined out in release mode.

https://github.com/BossKoopa/BWSR/commit/10b0ede9f01b818204d647ad05baa821d2650e2b
