### ISSUE TITLE
It's working without jailbreak in IOS?

### ISSUE THREAD

**Issue by Quangcha** [BossKoopa/BWSR#2]
Will it work on a non-jailbroken(Jailed)? thank you so much

**Comment by BossKoopa** [comment]
It is not possible to hook without bypassing certain security methods. Apple publishes a white paper every year which describes in detail which protections would prevent you from modifying the executable region of a page - if you defeat these protections this hooking method will work for you.

https://help.apple.com/pdf/security/en_US/apple-platform-security-guide.pdf
